server:
  port: 8008

spring:
  application:
    name: piratebay-backend
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/piratebay_db
    username: postgres
    password: postgres
